config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Steven C Hartley
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "sidekiq/web"
require "sidekiq-scheduler/web"

# For more information about routes, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "landing#index"

  # Sidekiq is our jobs server and keeps tabs on backround tasks
  if ENV["SIDEKIQ_USER"].present? && ENV["SIDEKIQ_PASSWORD"].present?
    # Mounting /sidekiq with basic auth
    mount Sidekiq::Web, at: "/sidekiq"

    Sidekiq::Web.use Rack::Auth::Basic  do |username, password|
      user_provided = ::Digest::SHA256.hexdigest(username)
      user_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USER"])

      password_provided = ::Digest::SHA256.hexdigest(password)
      password_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])

      ActiveSupport::SecurityUtils.secure_compare(user_provided, user_expected) &&
        ActiveSupport::SecurityUtils.secure_compare(password_provided, password_expected)
    end
  elsif ENV["SIDEKIQ_NO_PASSWORD"].present?
    # Mounting /sidekiq without password
    mount Sidekiq::Web, at: "/sidekiq"
  else
    # Not mounting /sidekiq
  end

  # Sets routes for account management actions.
  # This order seems to matter for tests.
  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :categories
  resources :credits
  resources :landing
  resources :memberships
  resources :themes
  resources :upgrades

  resources :reservations do
    resources :charges
    resources :nominations, id: /[^\/]+/
    resources :upgrades
  end

  # /operator are maintenance routes for support people
  scope :operator do
    resources :reservations do
      resources :credits
      resources :set_memberships
      resources :transfers, id: /[^\/]+/
    end
  end

  namespace :kiosk do
    root to: "memberships#index"

    resources :memberships, only: :index
    resources :reservations, only: [:new, :create] do
      resources :next_steps, only: :index
      resources :charges, only: [:new, :create]
    end
  end
end

app/controllers/credits_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# CreditsController allows us to list and grant account credit to a user
class CreditsController < ApplicationController
  before_action :authenticate_support!
  before_action :lookup_reservation!

  def new
    @amount_owed = AmountOwedForReservation.new(@reservation).amount_owed
    @credit = PlanCredit.new
  end

  def create
    credit_params = params.require(:plan_credit).permit(:amount)
    plan = PlanCredit.new(credit_params)
    if !plan.valid?
      flash[:error] = plan.errors.full_messages.to_sentence
      redirect_to @reservation
      return
    end

    ApplyCredit.new(@reservation, plan.money, audit_by: current_support.email).call
    flash[:notice] = "Credited ##{@reservation.membership_number} with #{plan.money.format}"
    redirect_to @reservation
  end
end

app/helpers/credits_helper.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


module CreditsHelper
  def pick_an_amount_instruction(max:)
    "Credit, up to #{max.format(with_currency: true)}"
  end
end

app/views/credits/new.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h1>Put Credit towards Membership #<%= @reservation.membership_number %></h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="l-panel">
        <p>
          Warning, this action will change the total owed on this membership.
        </p>

        <%= form_for(@credit, url: reservation_credits_path(@reservation)) do |credit_form| %>
          <div class="form-row align-items-center">
            <div class="col-auto">
              <label class="sr-only" for="inlineFormInputGroup">
                <%= pick_an_amount_instruction(max: @amount_owed) %>
              </label>

              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <%= @amount_owed.currency.symbol %>
                  </div>
                </div>

                <%=
                  credit_form.text_field(:amount,
                    required: true,
                    class: "form-control",
                    id: "first_name",
                    value: @amount_owed,
                    placeholder: pick_an_amount_instruction(max: @amount_owed),
                  )
                %>
              </div>
            </div>

            <div class="col-auto">
              <button type="submit" class="btn btn-primary mb-2">
                Credit Account
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="l-v-spacing">
        <%= render("reservation_card", reservation: @reservation) %>
      </div>
    </div>
  </div>
</section>