config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Steven C Hartley
# Copyright 2020 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "sidekiq/web"
require "sidekiq-scheduler/web"

# For more information about routes, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: "landing#index"

  # Sidekiq is our jobs server and keeps tabs on backround tasks
  if ENV["SIDEKIQ_USER"].present? && ENV["SIDEKIQ_PASSWORD"].present?
    # Mounting /sidekiq with basic auth
    mount Sidekiq::Web, at: "/sidekiq"

    Sidekiq::Web.use Rack::Auth::Basic  do |username, password|
      user_provided = ::Digest::SHA256.hexdigest(username)
      user_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USER"])

      password_provided = ::Digest::SHA256.hexdigest(password)
      password_expected = ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"])

      ActiveSupport::SecurityUtils.secure_compare(user_provided, user_expected) &&
        ActiveSupport::SecurityUtils.secure_compare(password_provided, password_expected)
    end
  elsif ENV["SIDEKIQ_NO_PASSWORD"].present?
    # Mounting /sidekiq without password
    mount Sidekiq::Web, at: "/sidekiq"
  else
    # Not mounting /sidekiq
  end

  # Sets routes for account management actions.
  # This order seems to matter for tests.
  devise_for :users
  devise_for :supports

  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :categories
  resources :credits
  resources :landing
  resources :memberships
  resources :themes
  resources :upgrades

  resources :reservations do
    resources :charges
    resources :nominations, id: /[^\/]+/
    resources :upgrades
  end

  # /operator are maintenance routes for support people
  scope :operator do
    resources :reservations do
      resources :credits
      resources :set_memberships
      resources :transfers, id: /[^\/]+/
    end
  end

  namespace :kiosk do
    root to: "memberships#index"

    resources :memberships, only: :index
    resources :reservations, only: [:new, :create] do
      resources :next_steps, only: :index
      resources :charges, only: [:new, :create]
    end
  end
end

app/controllers/transfers_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
class TransfersController < ApplicationController
  helper ReservationsHelper

  before_action :authenticate_support!
  before_action :setup_transfer, only: [:show, :update]

  def new
    @reservation = Reservation.find(params[:reservation_id])
    @detail = @reservation.active_claim.detail
  end

  def show
  end

  def update
    current_support.transaction do
      owner_detail = @transfer.detail

      service = ApplyTransfer.new(
        @transfer.reservation,
        from: @transfer.from_user,
        to: @transfer.to_user,
        audit_by: current_support.email,
        copy_details: @transfer.copy_details?,
      )
      new_claim = service.call
      if !new_claim
        flash[:error] = service.error_message
        redirect_to reservations_path
        return
      end

      MembershipMailer.transfer(
        from: @transfer.from_user.email,
        to: @transfer.to_user.email,
        owner_name: owner_detail&.to_s,
        membership_number: @transfer.reservation.membership_number,
      ).deliver_later

      flash[:notice] = %{
        Transferred membership ##{@transfer.reservation.membership_number}
        to #{@transfer.to_user.email}
      }

      redirect_to reservations_path
    end
  end

  private

  def setup_transfer
    @transfer = PlanTransfer.new(
      new_owner: params[:id],
      reservation_id: params[:reservation_id],
      copy_details: params.dig("plan_transfer", "copy_details"),
    )

    if !@transfer.valid?
      flash[:error] = @transfer.errors.full_messages.to_sentence
      redirect_to reservations_path
    end
  end
end

app/views/transfers/new.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>
<h1>Transferring Membership: Select transfer email</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <h2>
          From
          <%= @detail %>
          &lt;<%= @reservation.user.email %>&gt;
        </h2>

        <p>
          This process will send email to <%= @detail || @reservation.user.email %> and the new email address.
        </p>

        <p>
          Users listed here would have signed in at least once so we know they have access to their account
        </p>

        <table class="js-data-table table table-hover table-striped table-dark table-borderless table-responsive-lg">
          <thead>
            <th>Email</th>
            <th>Membership Details</th>
          </thead>
          <tbody>
            <%= User.eager_load(active_claims: :detail).find_each do |user| %>
              <tr>
                <td><%= link_to user.email, reservation_transfer_path(user.email, reservation_id: @reservation)  %></td>
                <td><%= user.active_claims.map(&:detail).map(&:to_s).to_sentence %></td>
              </p>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/transfers/show.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>
<h1>Transferring Membership: Confirm transfer</h1>
<section class="l-section">
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <%= form_for(@transfer, method: :patch, url: update_transfer_path(@transfer)) do |f| %>
          <h2>#<%= @transfer.reservation.membership_number %> <%= @transfer.detail %></h2>
          <p>Transferring from <%= @transfer.from_user.email %></p>
          <p>Transferring to <%= @transfer.to_user.email %><p>

          <div class="form-options">
            <%= f.check_box(:copy_details, class: "form-control form-control-m-checkbox", id: "copy_details") %>
            <label for="copy_details">Keep membership details? This includes name, badge name, and address</label>
          </div>

          <fieldset class="l-v-spacing">
            <div class="row">
              <div class="col-12 col-md-6">
                <div class="l-v-spacing">
                  <%= link_to "Go back to transfer list", new_reservation_transfer_path, class: "btn btn-m-full-width" %>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="l-v-spacing">
                  <input type="submit" value="Email users and transfer membership" class="btn btn-m-full-width">
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>